branch-defaults:
  default:
    environment: pau-api-dev
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: pau-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: udacity
  repository: null
  sc: null
  workspace_type: Application
