version: 2.1
orbs:
  node: circleci/node@4.1
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  Frontend_and_deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run: echo "aws s3 cp --recursive --acl public-read ./build $AWS_BUCKET_NAME"

  Api_build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build

  Api_deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run: echo "eb deploy"

workflows:
  deploy:
    jobs:
      - Frontend
      - Api_build
      - Api_deploy:
          context: aws
          application_name: pau-api
          default_region: us-east-1
          deploy:
            artifact: www/Archive.zip


