version: 2.1
orbs:
  node: circleci/node@4.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  Frontend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run: echo "aws s3 cp --recursive --acl public-read ./build $AWS_BUCKET_NAME"

  Api:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - eb/deploy:
          context: aws-creds
          app-dir: ./www
          application-name: pau-api
          environment-name: pau-api-dev
          filters:
            branches:
              only:
                - main

